const SEARCH_INDEX = [

  // 🍎 FRUITS
  { name: "Apple", type: "fruit" },
  { name: "Apricot", type: "fruit" },
  { name: "Avocado", type: "fruit" },
  { name: "Banana", type: "fruit" },
  { name: "Blueberry", type: "fruit" },
  { name: "Cherry", type: "fruit" },
  { name: "Coconut", type: "fruit" },
  { name: "Dragon Fruit", type: "fruit" },
  { name: "Durian", type: "fruit" },
  { name: "Fig", type: "fruit" },
  { name: "Grape", type: "fruit" },
  { name: "Grapefruit", type: "fruit" },
  { name: "Guava", type: "fruit" },
  { name: "Jackfruit", type: "fruit" },
  { name: "Kiwi", type: "fruit" },
  { name: "Lemon", type: "fruit" },
  { name: "Lychee", type: "fruit" },
  { name: "Mango", type: "fruit" },
  { name: "Melon", type: "fruit" },
  { name: "Orange", type: "fruit" },
  { name: "Papaya", type: "fruit" },
  { name: "Peach", type: "fruit" },
  { name: "Pear", type: "fruit" },
  { name: "Pineapple", type: "fruit" },
  { name: "Plum", type: "fruit" },
  { name: "Pomegranate", type: "fruit" },
  { name: "Raspberry", type: "fruit" },
  { name: "Starfruit", type: "fruit" },
  { name: "Strawberry", type: "fruit" },
  { name: "Watermelon", type: "fruit" },
  { name: "Passion Fruit", type: "fruit" },
  { name: "Mulberry", type: "fruit" },
  { name: "Mandarin", type: "fruit" },
  { name: "Cranberry", type: "fruit" },
  { name: "Blackberry", type: "fruit" },
  { name: "Custard Apple", type: "fruit" },
  { name: "Sapota", type: "fruit" },
  { name: "Tamarind", type: "fruit" },
  { name: "Physalis", type: "fruit" },
  { name: "Rambutan", type: "fruit" },
  { name: "Persimmon", type: "fruit" },
  { name: "Pomelo", type: "fruit" },
  { name: "Jujube", type: "fruit" },
  { name: "Star Gooseberry", type: "fruit" },
  { name: "Longan", type: "fruit" },
  { name: "Loquat", type: "fruit" },
  { name: "Kumquat", type: "fruit" },
  { name: "Salak", type: "fruit" },
  { name: "Ackee", type: "fruit" },
  { name: "Breadfruit", type: "fruit" },
  { name: "Carambola", type: "fruit" },
  { name: "Cherimoya", type: "fruit" },
  { name: "Sapodilla", type: "fruit" },
  { name: "Santol", type: "fruit" },
  { name: "Mangaba", type: "fruit" },
  { name: "Canistel", type: "fruit" },

  // 🥕 VEGETABLES
  { name: "Potato", type: "vegetable" },
  { name: "Sweet Potato", type: "vegetable" },
  { name: "Carrot", type: "vegetable" },
  { name: "Onion", type: "vegetable" },
  { name: "Garlic", type: "vegetable" },
  { name: "Beetroot", type: "vegetable" },
  { name: "Radish", type: "vegetable" },
  { name: "Turnip", type: "vegetable" },
  { name: "Rutabaga", type: "vegetable" },
  { name: "Celeriac", type: "vegetable" },
  { name: "Cassava", type: "vegetable" },
  { name: "Ginger", type: "vegetable" },
  { name: "Turmeric", type: "vegetable" },
  { name: "Daikon", type: "vegetable" },
  { name: "Parsnip", type: "vegetable" },
  { name: "Spinach", type: "vegetable" },
  { name: "Kale", type: "vegetable" },
  { name: "Cabbage", type: "vegetable" },
  { name: "Lettuce", type: "vegetable" },
  { name: "Swiss Chard", type: "vegetable" },
  { name: "Mustard Greens", type: "vegetable" },
  { name: "Bok Choy", type: "vegetable" },
  { name: "Collard Greens", type: "vegetable" },
  { name: "Arugula", type: "vegetable" },
  { name: "Romaine", type: "vegetable" },
  { name: "Broccoli", type: "vegetable" },
  { name: "Cauliflower", type: "vegetable" },
  { name: "Brussels Sprouts", type: "vegetable" },
  { name: "Kohlrabi", type: "vegetable" },
  { name: "Cabbage Red", type: "vegetable" },
  { name: "Tomato", type: "vegetable" },
  { name: "Bell Pepper", type: "vegetable" },
  { name: "Chili Pepper", type: "vegetable" },
  { name: "Cucumber", type: "vegetable" },
  { name: "Zucchini", type: "vegetable" },
  { name: "Eggplant", type: "vegetable" },
  { name: "Okra", type: "vegetable" },
  { name: "Pumpkin", type: "vegetable" },
  { name: "Butternut Squash", type: "vegetable" },
  { name: "Acorn Squash", type: "vegetable" },
  { name: "Parsley", type: "vegetable" },
  { name: "Coriander", type: "vegetable" },
  { name: "Cilantro", type: "vegetable" },
  { name: "Mint", type: "vegetable" },
  { name: "Rosemary", type: "vegetable" },
  { name: "Thyme", type: "vegetable" },
  { name: "Basil", type: "vegetable" },
  { name: "Lettuce Iceberg", type: "vegetable" },

  // 🌿 PLANTS
  { name: "Aloe Vera", type: "plant" },
  { name: "Snake Plant", type: "plant" },
  { name: "Spider Plant", type: "plant" },
  { name: "Peace Lily", type: "plant" },
  { name: "Pothos", type: "plant" },
  { name: "Monstera", type: "plant" },
  { name: "ZZ Plant", type: "plant" },
  { name: "Fiddle Leaf Fig", type: "plant" },
  { name: "Rubber Plant", type: "plant" },
  { name: "Lavender", type: "plant" },
  { name: "Sunflower", type: "plant" },
  { name: "Marigold", type: "plant" },
  { name: "Fern", type: "plant" },
  { name: "Cactus", type: "plant" },
  { name: "Orchid", type: "plant" },
  { name: "Curry Leaf", type: "plant" },
  { name: "Jade Plant", type: "plant" },
  { name: "Money Plant", type: "plant" },
  { name: "Tulsi", type: "plant" },
  { name: "Lemon Tree", type: "plant" },
  { name: "Bird of Paradise", type: "plant" },
  { name: "Bamboo", type: "plant" },
  { name: "Hibiscus", type: "plant" },
  { name: "Jasmine", type: "plant" }
];